/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arlaxad
 */
public class telacadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form telacadastroCliente
     */
    public telacadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusercli = new javax.swing.JTextField();
        txtsenhacli = new javax.swing.JTextField();
        btlimparcli = new javax.swing.JButton();
        btcadcli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cxsalario = new javax.swing.JCheckBox();
        cxcorrente = new javax.swing.JCheckBox();
        cxpoupanca = new javax.swing.JCheckBox();
        btCancel = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setClosable(true);
        setTitle("Tela de Cadastro de Cliente");

        jLabel1.setText("CADASTRAR CLIENTE");

        jLabel2.setText("Nome do Cliente");

        jLabel3.setText("Senha");

        btlimparcli.setText("Limpar");
        btlimparcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlimparcliActionPerformed(evt);
            }
        });

        btcadcli.setText("Cadastrar");
        btcadcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadcliActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo da Conta");

        cxsalario.setText("Salario");
        cxsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxsalarioActionPerformed(evt);
            }
        });

        cxcorrente.setText("Corrente");
        cxcorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxcorrenteActionPerformed(evt);
            }
        });

        cxpoupanca.setText("Poupança");
        cxpoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxpoupancaActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtusercli, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsenhacli, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btCancel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btlimparcli)
                            .addGap(18, 18, 18)
                            .addComponent(btcadcli))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(cxsalario)
                            .addGap(18, 18, 18)
                            .addComponent(cxcorrente)
                            .addGap(18, 18, 18)
                            .addComponent(cxpoupanca))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addComponent(txtusercli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtsenhacli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxsalario)
                    .addComponent(cxcorrente)
                    .addComponent(cxpoupanca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btlimparcli)
                    .addComponent(btcadcli)
                    .addComponent(btCancel))
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int conta = 0;
    private void btcadcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadcliActionPerformed
        String Nome = txtusercli.getText();
        String Senha = txtsenhacli.getText();
        String contaV = "";
        int quantidade, conversao, result;
        if (conta == 1) {

            quantidade = Nome.length();
            conversao = Integer.parseInt(Senha);
            result = (conversao * quantidade);
            String numcont = Integer.toString(result);
            contaV = "1234" + numcont;
        } else if (conta == 2) {

            quantidade = Nome.length();
            conversao = Integer.parseInt(Senha);
            result = (conversao * quantidade);
            String numcont = Integer.toString(result);
            contaV = "1122" + numcont;

        } else if (conta == 3) {

            quantidade = Nome.length();
            conversao = Integer.parseInt(Senha);
            result = (conversao * quantidade);
            String numcont = Integer.toString(result);
            contaV = "1455" + numcont;

        }
        File ArquivoCli = new File("C:\\Users\\Arlaxad\\Documents\\NetBeansProjects\\banco\\src\\Cliente\\" + contaV + ".txt");

        boolean existe = ArquivoCli.exists();

        if (existe == false) {
            boolean criou;
            try {
                criou = ArquivoCli.createNewFile();
                if (criou == true) {
                    FileWriter fw = new FileWriter(ArquivoCli);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write(Nome);
                    bw.write(",");
                    bw.write(Senha);
                    bw.write(",");
                    if (conta == 1) {

                        quantidade = Nome.length();
                        conversao = Integer.parseInt(Senha);
                        result = (conversao * quantidade);
                        String numcont = Integer.toString(result);
                        contaV = "1234" + numcont;
                        bw.write(contaV);
                        bw.write(",");
                        String saldo = "0";
                        bw.write(saldo);
                    } else if (conta == 2) {

                        quantidade = Nome.length();
                        conversao = Integer.parseInt(Senha);
                        result = (conversao * quantidade);
                        String numcont = Integer.toString(result);
                        contaV = "1122" + numcont;
                        bw.write(contaV);
                        bw.write(",");
                        String saldo = "0";
                        bw.write(saldo);
                    } else if (conta == 3) {

                        quantidade = Nome.length();
                        conversao = Integer.parseInt(Senha);
                        result = (conversao * quantidade);
                        String numcont = Integer.toString(result);
                        contaV = "1455" + numcont;
                        bw.write(contaV);
                        bw.write(",");
                        String saldo = "0";
                        bw.write(saldo);
                    }

                    bw.close();
                    fw.close();
                }
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso, seu numero da Conta é " + contaV);
                txtsenhacli.setText("");
                txtusercli.setText("");
                cxcorrente.setSelected(false);
                cxpoupanca.setSelected(false);
                cxsalario.setSelected(false);

            } catch (IOException ex) {
                Logger.getLogger(telacadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Já possui um cadastro com essa conta!");
        }

    }//GEN-LAST:event_btcadcliActionPerformed

    private void cxsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxsalarioActionPerformed
        cxcorrente.setSelected(false);
        cxpoupanca.setSelected(false);
        conta = 1;
    }//GEN-LAST:event_cxsalarioActionPerformed

    private void cxcorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxcorrenteActionPerformed
        cxpoupanca.setSelected(false);
        cxsalario.setSelected(false);
        conta = 2;
    }//GEN-LAST:event_cxcorrenteActionPerformed

    private void cxpoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxpoupancaActionPerformed
        cxcorrente.setSelected(false);
        cxsalario.setSelected(false);
        conta = 3;
    }//GEN-LAST:event_cxpoupancaActionPerformed

    private void btlimparcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlimparcliActionPerformed
        txtsenhacli.setText("");
        txtusercli.setText("");
    }//GEN-LAST:event_btlimparcliActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
       this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btcadcli;
    private javax.swing.JButton btlimparcli;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cxcorrente;
    private javax.swing.JCheckBox cxpoupanca;
    private javax.swing.JCheckBox cxsalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtsenhacli;
    private javax.swing.JTextField txtusercli;
    // End of variables declaration//GEN-END:variables
}
