/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arlaxad
 */
public class telaPagamento extends javax.swing.JInternalFrame {

    String conta;

    /**
     * Creates new form telaPagamento
     */
    public telaPagamento() {
        initComponents();
    }

    public telaPagamento(String Conta) {
        this.conta = Conta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btPagar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Tela de Pagamento");

        jLabel1.setText("VALOR A SER PAGO:");

        btPagar.setText("Pagar");
        btPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCancel)
                        .addGap(12, 12, 12)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPagar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPagar)
                    .addComponent(btLimpar)
                    .addComponent(btCancel))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtValor.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarActionPerformed
        String arrayV[] = new String[4];
        String valores = "";
        File ArquivoCli = new File("\\Users\\Arlaxad\\Documents\\NetBeansProjects\\banco\\src\\Cliente\\" + conta + ".txt");
        boolean existe = ArquivoCli.exists();
        if (existe == true) {
            FileReader fr;
            try {
                fr = new FileReader(ArquivoCli);
                try (BufferedReader br = new BufferedReader(fr)) {
                    while (br.ready()) {
                        valores = br.readLine();
                    }
                    arrayV = valores.split(",");
                }
                fr.close();

                float v = Float.parseFloat(arrayV[3]);
                float v2 = Float.parseFloat(txtValor.getText());
                if (v < v2) {
                    JOptionPane.showMessageDialog(null,"Saldo Insuficiente\n Saldo atual: "+v);
                } else {
                    float total = v - v2;
                    String trans = Float.toString(total);

                    try (FileWriter fw = new FileWriter(ArquivoCli)) {
                        try (BufferedWriter bw = new BufferedWriter(fw)) {
                            bw.write(arrayV[0]);
                            bw.write(",");
                            bw.write(arrayV[1]);
                            bw.write(",");
                            bw.write(arrayV[2]);
                            bw.write(",");
                            bw.write(trans);
                        }
                        
                        fw.close();
                    }
                    txtValor.setText("");
                    JOptionPane.showMessageDialog(null, "O valor de "+v2+" reais foi pago!");
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(telaSaldoCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(telaSaldoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btPagarActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
