/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arlaxad
 */
public class telaloginfun extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaloginfun
     */
    public telaloginfun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginfunuser = new javax.swing.JLabel();
        loginfunsenha = new javax.swing.JLabel();
        txtloginfunuser = new javax.swing.JTextField();
        btloginfun = new javax.swing.JButton();
        txtloginfunsenha = new javax.swing.JPasswordField();
        btCancel = new javax.swing.JButton();

        setClosable(true);
        setTitle("Login Funcionario");

        loginfunuser.setText("Usuario");

        loginfunsenha.setText("Senha");

        btloginfun.setText("Entrar");
        btloginfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginfunActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btloginfun))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(loginfunuser)
                        .addComponent(loginfunsenha)
                        .addComponent(txtloginfunuser, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(txtloginfunsenha)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(loginfunuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtloginfunuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginfunsenha)
                .addGap(18, 18, 18)
                .addComponent(txtloginfunsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btloginfun)
                    .addComponent(btCancel))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btloginfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginfunActionPerformed
        String Nome = txtloginfunuser.getText();
        String Senha = txtloginfunsenha.getText();
        String Valores = "";
        String arrayFun[] = new String[2];
        File ArquivoFunc = new File("\\Users\\Arlaxad\\Documents\\NetBeansProjects\\banco\\src\\Funcionario\\" + Nome + ".txt");
        boolean existe = ArquivoFunc.exists();
        try {
            FileReader fr = new FileReader(ArquivoFunc);
            BufferedReader br = new BufferedReader(fr);
            while(br.ready()){
                Valores = br.readLine();
            }
            br.close();
            fr.close();
            arrayFun = Valores.split(",");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(telaloginfun.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(telaloginfun.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(existe == true){
            if(arrayFun[0].equals(Nome)&&arrayFun[1].equals(Senha)){
                txtloginfunsenha.setText("");
                txtloginfunuser.setText("");
                new telaFuncionario().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Senha Incorreta!");
                txtloginfunsenha.setText("");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Funcionario não cadastrado!");
            txtloginfunsenha.setText("");
            txtloginfunuser.setText("");
        }
        
    }//GEN-LAST:event_btloginfunActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btloginfun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginfunsenha;
    private javax.swing.JLabel loginfunuser;
    private javax.swing.JPasswordField txtloginfunsenha;
    private javax.swing.JTextField txtloginfunuser;
    // End of variables declaration//GEN-END:variables
}
