/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arlaxad
 */
public class telaTransferencia extends javax.swing.JInternalFrame {

    String conta;

    /**
     * Creates new form telaTransferencia
     */
    public telaTransferencia() {
        initComponents();
    }

    public telaTransferencia(String Conta) {
        this.conta = Conta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtContaRec = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        brLimpar = new javax.swing.JButton();
        btTransferir = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Tela de Transferencia");

        jLabel1.setText("Numero da conta do receptor:");

        jLabel2.setText("Valor a ser Transferido");

        brLimpar.setText("Limpar");
        brLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brLimparActionPerformed(evt);
            }
        });

        btTransferir.setText("Transferir");
        btTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferirActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContaRec)
                    .addComponent(txtValor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTransferir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContaRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brLimpar)
                    .addComponent(btTransferir)
                    .addComponent(btCancel))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brLimparActionPerformed
        txtContaRec.setText("");
        txtValor.setText("");
    }//GEN-LAST:event_brLimparActionPerformed

    private void btTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferirActionPerformed
        String arrayV[] = new String[4];
        String arrayR[] = new String[4];
        String valores = "";
        String ContaT = txtContaRec.getText();
        float result = Float.parseFloat(txtValor.getText());
        float valor_atual = 0;
        File ArquivoCli = new File("\\Users\\Arlaxad\\Documents\\NetBeansProjects\\banco\\src\\Cliente\\" + conta + ".txt");
        File ArquivoCliRe = new File("\\Users\\Arlaxad\\Documents\\NetBeansProjects\\banco\\src\\Cliente\\" + ContaT + ".txt");
        boolean existe = ArquivoCli.exists();
        boolean existeContaRec = ArquivoCliRe.exists();
        if (existe == true) {
            FileReader fr;
            try {
                fr = new FileReader(ArquivoCli);
                try (BufferedReader br = new BufferedReader(fr)) {
                    while (br.ready()) {
                        valores = br.readLine();
                    }

                    arrayV = valores.split(",");
                    br.close();
                }
                fr.close();

            } catch (FileNotFoundException ex) {
                Logger.getLogger(telaSaldoCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(telaSaldoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            valor_atual = Float.parseFloat(arrayV[3]);
        }
        if (existeContaRec == false || valor_atual < result) {
            JOptionPane.showMessageDialog(null, "A conta referida não foi encontrada ou valor que desejas transferir não está disponivel!\n valor atual na conta " + valor_atual);
        }
        if (existeContaRec == true && valor_atual >= result) {
            FileReader fr;
            try {
                fr = new FileReader(ArquivoCliRe);
                try (BufferedReader br = new BufferedReader(fr)) {
                    while (br.ready()) {
                        valores = br.readLine();
                    }
                    arrayR = valores.split(",");
                }
                fr.close();

            } catch (FileNotFoundException ex) {
                Logger.getLogger(telaSaldoCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(telaSaldoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

            float valor_retirado = valor_atual - result;
            float valor_atual_rec = Float.parseFloat(arrayR[3]);
            float valor_alt_rec = valor_atual_rec + result;
            String vt = Float.toString(valor_retirado);
            String vr = Float.toString(valor_alt_rec);
            FileWriter fw;
            try {
                fw = new FileWriter(ArquivoCli);
                try (BufferedWriter bw = new BufferedWriter(fw)) {
                    bw.write(arrayV[0]);
                    bw.write(",");
                    bw.write(arrayV[1]);
                    bw.write(",");
                    bw.write(arrayV[2]);
                    bw.write(",");
                    bw.write(vt);
                    bw.close();
                }

                fw.close();

                try (FileWriter fwr = new FileWriter(ArquivoCliRe)) {
                    BufferedWriter bwr = new BufferedWriter(fwr);
                    bwr.write(arrayR[0]);
                    bwr.write(",");
                    bwr.write(arrayR[1]);
                    bwr.write(",");
                    bwr.write(arrayR[2]);
                    bwr.write(",");
                    bwr.write(vr);
                    bwr.close();
                    fwr.close();
                }

            } catch (IOException ex) {
                Logger.getLogger(telaTransferencia.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Transação efetuada com sucesso!");
            txtContaRec.setText("");
            txtValor.setText("");
        }


    }//GEN-LAST:event_btTransferirActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brLimpar;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtContaRec;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
